"""add per-project github token

Revision ID: 2a1a5680df76
Revises: c5899b7c4c3f
Create Date: 2026-08-17 15:52:08.631151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a1a5680df76'
down_revision: Union[str, None] = 'c5899b7c4c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('github_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'github_token')
    # ### end Alembic commands ###
